'use strict';
(() => {
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d');
const W=1280,H=800,TAU=Math.PI*2,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),rand=(a,b)=>a+Math.random()*(b-a),distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const bounds={left:192,right:1156,top:206,bottom:662};
const pageNames=['EL MARGEN CONTRAATACA','ASUNTOS PUNTIAGUDOS','EL CORTE FINAL'];
let state='menu',beforePause='play',clock=0,last=0,introTime=0,page=0,wave=0,score=0,kills=0,combo=0,bestCombo=0,comboTime=0,runTime=0;
let player,enemies=[],spawns=[],shots=[],particles=[],texts=[],swings=[],stains=[],drops=[],ghosts=[],nextId=0;
let spawnQueue=[],spawnWait=0,waveWait=0,banner='',bannerTime=0,shake=0,freeze=0,flash=0,turn=0,won=false;
let keys=new Set(),pointer={x:650,y:400,down:false,used:false},stick={x:0,y:0},touchAttack=false;
let musicTime=0,musicStep=0,audio=null,master=null,muted=false;
let best=0;try{best=Number(localStorage.getItem('trazo-best'))||0;muted=localStorage.getItem('trazo-muted')==='1'}catch{}
const pageCanvas=document.createElement('canvas');pageCanvas.width=W;pageCanvas.height=H;Art.use(pageCanvas.getContext('2d'));Art.sheet();Art.use(ctx);
function audioInit(){if(audio){if(audio.state==='suspended')audio.resume().catch(()=>{});return}try{audio=new (window.AudioContext||window.webkitAudioContext)();master=audio.createGain();master.gain.value=muted?0:.25;master.connect(audio.destination)}catch{}}
function tone(freq,length=.12,type='triangle',volume=.18,slide=0,delay=0){if(!audio||muted||audio.state!=='running')return;const at=audio.currentTime+delay,o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(Math.max(20,freq),at);if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(25,slide),at+length);g.gain.setValueAtTime(.0001,at);g.gain.exponentialRampToValueAtTime(volume,at+.005);g.gain.exponentialRampToValueAtTime(.0001,at+length);o.connect(g);g.connect(master);o.start(at);o.stop(at+length+.02);o.onended=()=>{o.disconnect();g.disconnect()}}
function hiss(length=.1,volume=.2,filter=1600){if(!audio||muted||audio.state!=='running')return;const n=Math.ceil(audio.sampleRate*length),buffer=audio.createBuffer(1,n,audio.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<n;i++)data[i]=(Math.random()*2-1)*Math.pow(1-i/n,2);const source=audio.createBufferSource(),f=audio.createBiquadFilter(),g=audio.createGain();source.buffer=buffer;f.type='bandpass';f.frequency.value=filter;g.gain.value=volume;source.connect(f);f.connect(g);g.connect(master);source.start();source.onended=()=>{source.disconnect();f.disconnect();g.disconnect()}}
function sfx(type){if(type==='slash'){hiss(.1,.38,3300);tone(190,.06,'triangle',.1,80)}if(type==='hit'){tone(105,.095,'square',.13,43);hiss(.09,.4,750)}if(type==='kill'){hiss(.16,.38,1300);tone(400,.11,'triangle',.17,750)}if(type==='hurt'){tone(130,.22,'sawtooth',.2,48);hiss(.15,.3,450)}if(type==='dash'){hiss(.15,.32,4000);tone(350,.1,'sine',.1,650)}if(type==='special'){hiss(.6,.6,1400);[196,293.66,392,587.3].forEach((f,i)=>tone(f,.5,'triangle',.15,0,i*.06))}if(type==='page'){hiss(.4,.45,2000);[261.6,329.6,392].forEach((f,i)=>tone(f,.2,'triangle',.15,0,i*.08))}if(type==='win'){[261.6,329.6,392,523.25,659.25,784].forEach((f,i)=>tone(f,.45,'triangle',.18,0,i*.12))}if(type==='pick')tone(720,.14,'sine',.15,1080)}
function music(dt){if(!audio||muted||state!=='play')return;musicTime-=dt;if(musicTime>0)return;musicTime+=.235;const seq=[0,7,12,7,3,10,15,10,5,12,17,12,3,10,7,10],root=page===2?146.83:130.81;const n=seq[musicStep%16];tone(root*Math.pow(2,n/12),.18,'triangle',.046);if(musicStep%4===0)tone(root/2,.24,'sine',.15);if(musicStep%4===2)hiss(.035,.065,3000);musicStep++}
function syncSound(){ $('sound').textContent='SONIDO: '+(muted?'NO':'SÍ');$('sound').setAttribute('aria-pressed',String(!muted));if(master)master.gain.value=muted?0:.25;try{localStorage.setItem('trazo-muted',muted?'1':'0')}catch{}}
function announce(text){$('announce').textContent=text}
function setState(s){state=s;$('menu').hidden=s!=='menu';$('intro').hidden=s!=='intro';$('hud').hidden=!['play','pause','upgrade','dead','win'].includes(s);$('pause').hidden=s!=='play';$('touch').hidden=s!=='play';$('stage').classList.toggle('playing',s!=='menu');if(s!=='play')releaseControls();if(s==='play')$('dialog').hidden=true}
function releaseControls(){keys.clear();pointer.down=false;touchAttack=false;stick.x=stick.y=0;$('stick').querySelector('i').style.transform='';}
function dialog(kicker,title,text,options,label,action){$('dialog-kicker').textContent=kicker;$('dialog-title').textContent=title;$('dialog-text').textContent=text;$('choices').replaceChildren();for(const opt of options||[]){const b=document.createElement('button');b.className='choice';const strong=document.createElement('strong'),span=document.createElement('span');strong.textContent=opt.title;span.textContent=opt.text;b.append(strong,span);b.onclick=opt.action;$('choices').append(b)}$('continue').hidden=!label;$('continue').textContent=label||'';$('continue').onclick=action;$('dialog').hidden=false;announce(title);queueMicrotask(()=>($('choices').firstElementChild||$('continue')).focus())}
function newPlayer(){return{x:610,y:452,hp:6,maxHp:6,angle:-.5,walk:0,invuln:0,attack:0,attackCd:0,chain:0,chainTime:0,dash:0,dashCd:0,dashX:0,dashY:0,ink:0,damage:1,speed:245,inkGain:1,dashPower:.7,dashHits:new Set()}}
function beginIntro(){audioInit();$('dialog').hidden=true;introTime=0;setState('intro');sfx('page');if(reduced)beginRun()}
function beginRun(){player=newPlayer();page=0;wave=0;score=0;kills=0;combo=0;bestCombo=0;comboTime=0;runTime=0;won=false;enemies=[];spawns=[];shots=[];particles=[];texts=[];swings=[];stains=[];drops=[];ghosts=[];spawnQueue=[];nextId=0;shake=0;freeze=0;flash=0;turn=.8;setState('play');nextWave();updateHud();announce('Página 1. Mueve con WASD o flechas, ataca con J y esquiva con espacio.')}
function nextWave(){wave++;waveWait=0;spawnWait=1.5;banner=wave===1?pageNames[page]:wave===3&&page===2?'ALGUIEN QUIERE RECORTARTE':`OLEADA ${wave}`;bannerTime=2.5;
  if(page===2&&wave===3){spawnQueue=['boss','eraser','pencil'];sfx('page')}
  else{const n=[4,6,8][wave-1]+page*2;spawnQueue=Array.from({length:n},(_,i)=>page===0?(i%3===2?'clip':'eraser'):['eraser','clip','pencil'][i%3])}
  announce(`${pageNames[page]}. Oleada ${wave} de 3.`);
}
function spawn(type){let x,y,tries=0;do{x=rand(bounds.left+45,bounds.right-45);y=rand(bounds.top+45,bounds.bottom-30)}while(distance({x,y},player)<240&&++tries<24);spawns.push({x,y,type,t:1.05});}
function makeEnemy(s){const boss=s.type==='boss',hp=boss?95:s.type==='eraser'?3+page*.7:s.type==='clip'?2.2+page*.6:2.6+page*.7;return{id:nextId++,x:s.x,y:s.y,type:s.type,hp,maxHp:hp,r:boss?52:s.type==='eraser'?25:21,speed:boss?57:s.type==='clip'?105:70,cool:rand(1,2),wind:0,charge:0,vx:0,vy:0,flash:0,knockX:0,knockY:0,phase:0,cycle:0,dead:false}}
function nearest(range=230){let best=null,d=range;for(const e of enemies){const n=distance(player,e);if(!e.dead&&n<d){d=n;best=e}}return best}
function attack(){if(state!=='play'||player.attackCd>0||player.dash>0)return;const target=nearest(205);if(target)player.angle=Math.atan2(target.y-player.y,target.x-player.x);else if(pointer.used)player.angle=Math.atan2(pointer.y-player.y,pointer.x-player.x);
  if(player.chainTime<=0)player.chain=0;player.chain=(player.chain+1)%3;player.chainTime=.9;const heavy=player.chain===0;player.attack=.19;player.attackCd=heavy?.36:.225;
  const radius=heavy?122:100;swings.push({x:player.x,y:player.y-15,a:player.angle,t:.22,max:.22,heavy,r:radius});sfx('slash');
  for(const e of enemies){const a=Math.atan2(e.y-player.y,e.x-player.x),delta=Math.atan2(Math.sin(a-player.angle),Math.cos(a-player.angle));if(!e.dead&&distance(player,e)<radius+e.r&&Math.abs(delta)<(heavy?2:1.45)){hit(e,player.damage*(heavy?1.9:1),heavy?310:175);}}
  player.x=clamp(player.x+Math.cos(player.angle)*8,bounds.left,bounds.right);player.y=clamp(player.y+Math.sin(player.angle)*8,bounds.top,bounds.bottom);
}
function dash(){if(state!=='play'||player.dashCd>0)return;let {x,y}=movement();if(Math.hypot(x,y)<.1){x=Math.cos(player.angle);y=Math.sin(player.angle)}const l=Math.hypot(x,y)||1;player.dashX=x/l;player.dashY=y/l;player.angle=Math.atan2(y,x);player.dash=.19;player.dashCd=.72;player.invuln=Math.max(player.invuln,.29);player.dashHits.clear();sfx('dash');burst(player.x,player.y,10,Art.blue,130)}
function special(){if(state!=='play'||player.ink<100)return;player.ink=0;player.invuln=1;shake=14;flash=.16;freeze=.06;swings.push({x:player.x,y:player.y,a:0,t:.7,max:.7,heavy:true,r:360,special:true});sfx('special');float('¡GARABATO!',player.x,player.y-80,Art.blue,46);for(const e of enemies)if(distance(player,e)<385)hit(e,6*player.damage,490);shots=shots.filter(s=>distance(player,s)>410);burst(player.x,player.y,65,Art.blue,540)}
function burst(x,y,n,color,speed=210){for(let i=0;i<n;i++){const a=rand(0,TAU),v=rand(speed*.2,speed);particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,t:rand(.22,.6),max:.6,r:rand(1.7,5.4),color})}if(particles.length>650)particles.splice(0,particles.length-650)}
function float(text,x,y,color=Art.ink,size=26){texts.push({text,x,y,color,size,t:.85,max:.85})}
function hit(e,damage,force){if(e.dead)return;e.hp-=damage;e.flash=.16;const a=Math.atan2(e.y-player.y,e.x-player.x);e.knockX=Math.cos(a)*force*(e.type==='boss'?.12:1);e.knockY=Math.sin(a)*force*(e.type==='boss'?.12:1);if(e.type!=='boss'){e.wind=0;e.charge=0;e.cool=Math.max(e.cool,.5)}combo++;bestCombo=Math.max(bestCombo,combo);comboTime=3;player.ink=clamp(player.ink+7*player.inkGain,0,100);shake=Math.max(shake,damage>1.5?8:4);freeze=Math.max(freeze,.035);burst(e.x,e.y,damage>1.5?14:8,e.type==='eraser'?Art.red:Art.blue);sfx('hit');
  if(e.hp<=0){e.dead=true;kills++;const points=(e.type==='boss'?1500:80)*Math.min(5,1+Math.floor(combo/5));score+=points;float('+'+points,e.x,e.y-30,Art.blue,26);player.ink=clamp(player.ink+8,0,100);burst(e.x,e.y,24,e.type==='eraser'?Art.red:Art.blue,290);stains.push({x:e.x,y:e.y,r:rand(12,22),color:e.type==='eraser'?'#cc696516':'#327c9818',seed:rand(0,100)});if(stains.length>75)stains.shift();if(e.type==='boss'){won=true}else if(kills%7===0)drops.push({x:e.x,y:e.y,type:'heart',t:14});sfx('kill')}
}
function hurt(damage=1,source=player){if(player.invuln>0||state!=='play')return;player.hp=Math.max(0,player.hp-damage);player.invuln=1.15;combo=0;shake=14;flash=.13;freeze=.065;sfx('hurt');burst(player.x,player.y,22,Art.red);float('¡AU!',player.x,player.y-65,Art.red,35);const a=Math.atan2(player.y-source.y,player.x-source.x);player.x=clamp(player.x+Math.cos(a)*22,bounds.left,bounds.right);player.y=clamp(player.y+Math.sin(a)*22,bounds.top,bounds.bottom);announce(`Vida: ${player.hp} de ${player.maxHp}.`);if(player.hp<=0)endRun(false)}
function movement(){let x=Number(keys.has('KeyD')||keys.has('ArrowRight'))-Number(keys.has('KeyA')||keys.has('ArrowLeft'))+stick.x,y=Number(keys.has('KeyS')||keys.has('ArrowDown'))-Number(keys.has('KeyW')||keys.has('ArrowUp'))+stick.y;const l=Math.hypot(x,y);if(l>1){x/=l;y/=l}return{x,y}}
function fire(e,angle,speed=245){shots.push({x:e.x,y:e.y-7,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed,angle,t:5,r:7})}
function enemyUpdate(e,dt){
  if(e.dead)return;e.flash=Math.max(0,e.flash-dt);const d=distance(e,player),a=Math.atan2(player.y-e.y,player.x-e.x),boss=e.type==='boss',rage=boss&&e.hp<e.maxHp*.5;
  e.x+=e.knockX*dt;e.y+=e.knockY*dt;e.knockX*=Math.exp(-dt*10);e.knockY*=Math.exp(-dt*10);e.cool-=dt;
  if(e.charge>0){e.charge-=dt;e.x+=e.vx*dt;e.y+=e.vy*dt;if(distance(e,player)<e.r+17)hurt(boss?2:1,e)}
  else if(e.wind>0){e.wind-=dt;if(e.wind<=0){e.cycle++;if(e.type==='pencil'){fire(e,e.aim,270+page*20);if(page===2){fire(e,e.aim-.22,260);fire(e,e.aim+.22,260)}e.cool=2.5}
    else{const v=boss?(rage?620:485):e.type==='clip'?430:350;e.vx=Math.cos(e.aim)*v;e.vy=Math.sin(e.aim)*v;e.charge=boss?.65:e.type==='clip'?.38:.32;e.cool=boss?1.8:1.5;if(boss&&e.cycle%2===0){for(let i=0;i<8;i++)fire(e,TAU*i/8+clock*.2,rage?255:210)}}}}
  else {const speed=e.speed*(rage?1.4:1);if(e.type==='pencil'){if(d>335){e.x+=Math.cos(a)*speed*dt;e.y+=Math.sin(a)*speed*dt}else if(d<195){e.x-=Math.cos(a)*speed*dt;e.y-=Math.sin(a)*speed*dt}if(e.cool<=0){e.wind=.8;e.aim=a}}
    else{e.x+=Math.cos(a)*speed*dt;e.y+=Math.sin(a)*speed*dt;if(e.cool<=0&&d<(boss?570:e.type==='clip'?320:190)){e.wind=boss?(rage?.65:.95):.62;e.aim=a}}
    if(d<e.r+16)hurt(boss?2:1,e);
  }
  e.x=clamp(e.x,bounds.left-10,bounds.right+10);e.y=clamp(e.y,bounds.top+10,bounds.bottom);
}
function chooseUpgrade(){setState('upgrade');shots=[];const opts=[{title:'PUNTA AFILADA',text:'+35 % de daño. Para dejar huella.',action:()=>advancePage(()=>player.damage*=1.35)},{title:'MÁS PAPEL',text:'+2 de vida máxima y cura completa.',action:()=>advancePage(()=>{player.maxHp+=2;player.hp=player.maxHp})},{title:'TINTA FRESCA',text:'+45 % de carga del garabato. Especial listo.',action:()=>advancePage(()=>{player.inkGain*=1.45;player.ink=100})}];dialog(`PÁGINA ${page+1} COMPLETADA`,'Deja tu marca.','Elige una mejora y pasa página. Recuperas 2 corazones.',opts,null,null);sfx('page')}
function advancePage(apply){apply();player.hp=Math.min(player.maxHp,player.hp+2);page++;wave=0;enemies=[];spawns=[];stains=[];particles=[];texts=[];shots=[];drops=[];ghosts=[];swings=[];player.x=610;player.y=452;player.invuln=1.5;combo=0;turn=.85;setState('play');nextWave();sfx('page')}
function endRun(victory){if(state!=='play')return;score=Math.floor(score);if(score>best){best=score;try{localStorage.setItem('trazo-best',String(best))}catch{}}setState(victory?'win':'dead');sfx(victory?'win':'hurt');const minutes=Math.floor(runTime/60),seconds=String(Math.floor(runTime%60)).padStart(2,'0');const rank=victory?(player.hp>=4?'S':bestCombo>=20?'A':'B'):'—';dialog(victory?'LA LIBRETA ES TUYA':'TODAVÍA QUEDA PAPEL',victory?'Imposible de borrar.':'Era solo un borrador.',`${victory?'Las tijeras caen. Tu historia se queda.':'Un garabato nunca se rinde.'}\n${score.toLocaleString('es-ES')} puntos · combo máximo ${bestCombo} · ${minutes}:${seconds}${victory?' · rango '+rank:''}\nRécord en este dispositivo: ${best.toLocaleString('es-ES')}`,null,victory?'OTRA REBELIÓN ↗':'VOLVER A DIBUJAR ↗',()=>{audioInit();beginRun()})}
function pause(){if(state==='pause'){setState(beforePause);$('dialog').hidden=true;last=performance.now();return}if(state!=='play'&&state!=='intro')return;beforePause=state;setState('pause');dialog('RESPIRA UN MOMENTO','Lápiz en alto.','Tu garabato te espera justo aquí.',null,'SEGUIR DIBUJANDO ↗',()=>{setState(beforePause);$('dialog').hidden=true;last=performance.now();audioInit()})}
function updateHud(){if(!player)return;$('hearts').innerHTML=Array.from({length:player.maxHp},(_,i)=>`<span aria-hidden="true" class="heart${i>=player.hp?' empty':''}">♥</span>`).join('');$('hearts').setAttribute('aria-label',`Vida ${player.hp} de ${player.maxHp}`);$('ink-fill').style.width=player.ink+'%';$('ink-label').textContent=player.ink>=100?'¡GARABATO LISTO! · E':'GARABATO · '+Math.floor(player.ink)+' %';$('special').classList.toggle('ready',player.ink>=100);$('special').disabled=player.ink<100;$('touch-special').disabled=player.ink<100;$('touch-dash').disabled=player.dashCd>0;$('page-label').textContent=`PÁGINA 0${page+1} / 03`;$('wave-label').textContent=`OLEADA ${wave} / 3`;$('score').textContent=String(score).padStart(6,'0');$('combo').hidden=combo<3;$('combo').querySelector('strong').textContent=combo+'×';const boss=enemies.find(e=>e.type==='boss'&&!e.dead);$('boss-hud').hidden=!boss;if(boss)$('boss-fill').style.width=Math.max(0,boss.hp/boss.maxHp*100)+'%';}
let hudTime=0;
function update(dt){
  clock+=dt;music(dt);shake=Math.max(0,shake-dt*40);flash=Math.max(0,flash-dt);turn=Math.max(0,turn-dt);
  if(state==='intro'){introTime+=dt;const s=introTime<2.6?'Toda gran historia empieza en una página en blanco.':introTime<5?'Esta empezó con un garabato.':introTime<7.6?'La papelería tenía otros planes.':'Y tú… un lápiz con muy mala leche.';$('subtitle').innerHTML='<span>'+s+'</span>';if(introTime>=10.4)beginRun();return}
  if(state!=='play')return;
  runTime+=dt;bannerTime=Math.max(0,bannerTime-dt);comboTime-=dt;if(comboTime<=0)combo=0;player.invuln=Math.max(0,player.invuln-dt);player.attack=Math.max(0,player.attack-dt);player.attackCd=Math.max(0,player.attackCd-dt);player.chainTime-=dt;player.dashCd=Math.max(0,player.dashCd-dt);
  const move=movement();player.walk=Math.min(1,Math.hypot(move.x,move.y));
  if(player.dash>0){player.dash-=dt;player.x+=player.dashX*760*dt;player.y+=player.dashY*760*dt;if(ghosts.length===0||ghosts[ghosts.length-1].t<.15)ghosts.push({x:player.x,y:player.y,a:player.angle,t:.2});for(const e of enemies)if(!e.dead&&distance(e,player)<e.r+30&&!player.dashHits.has(e.id)){player.dashHits.add(e.id);hit(e,player.dashPower,190)}}
  else{player.x+=move.x*player.speed*dt;player.y+=move.y*player.speed*dt;if(player.walk>.1&&player.attack<=0)player.angle=Math.atan2(move.y,move.x)}
  player.x=clamp(player.x,bounds.left,bounds.right);player.y=clamp(player.y,bounds.top,bounds.bottom);
  if(keys.has('KeyJ')||pointer.down||touchAttack)attack();
  spawnWait-=dt;if(spawnQueue.length&&spawnWait<=0){spawn(spawnQueue.shift());spawnWait=page===2&&wave===3?1.9:.7}
  for(const s of spawns){s.t-=dt;if(s.t<=0)enemies.push(makeEnemy(s))}spawns=spawns.filter(s=>s.t>0);
  for(const e of enemies)enemyUpdate(e,dt);
  // Keep charging enemies readable; separate only enemies that are walking.
  for(let i=0;i<enemies.length;i++)for(let j=i+1;j<enemies.length;j++){const a=enemies[i],b=enemies[j];if(a.dead||b.dead||a.charge>0||b.charge>0)continue;const d=distance(a,b),r=a.r+b.r;if(d>0&&d<r){const k=(r-d)*.5,dx=(a.x-b.x)/d*k,dy=(a.y-b.y)/d*k;a.x+=dx;a.y+=dy;b.x-=dx;b.y-=dy}}
  for(const s of shots){s.t-=dt;s.x+=s.vx*dt;s.y+=s.vy*dt;if(distance(s,player)<22){hurt(1,s);s.t=0}if(s.x<170||s.x>1190||s.y<175||s.y>710)s.t=0}shots=shots.filter(s=>s.t>0);
  for(const p of particles){p.t-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=Math.exp(-dt*6);p.vy*=Math.exp(-dt*6)}particles=particles.filter(p=>p.t>0);
  for(const t of texts){t.t-=dt;t.y-=dt*36}texts=texts.filter(t=>t.t>0);
  for(const s of swings)s.t-=dt;swings=swings.filter(s=>s.t>0);
  for(const g of ghosts)g.t-=dt;ghosts=ghosts.filter(g=>g.t>0);
  for(const d of drops){d.t-=dt;if(distance(player,d)<40){player.hp=Math.min(player.maxHp,player.hp+1);d.t=0;float('+1 ♥',player.x,player.y-60,Art.red);sfx('pick')}}drops=drops.filter(d=>d.t>0);
  enemies=enemies.filter(e=>!e.dead);
  if(state!=='play')return;
  if(won){waveWait+=dt;if(waveWait>1.1)endRun(true)}
  else if(!enemies.length&&!spawns.length&&!spawnQueue.length){waveWait+=dt;if(waveWait>1.5){if(wave<3)nextWave();else if(page<2)chooseUpgrade()}}
  hudTime-=dt;if(hudTime<=0){updateHud();hudTime=.08}
}
function render(){Art.use(ctx);ctx.clearRect(0,0,W,H);
  if(state==='menu'||state==='help'){Art.cover(clock);return}
  if(state==='intro'||state==='pause'&&beforePause==='intro'){Art.opening(introTime);return}
  ctx.save();if(shake>0&&!reduced)ctx.translate(rand(-shake,shake),rand(-shake,shake));ctx.drawImage(pageCanvas,0,0);
  Art.text('0'+(page+1),1160,686,28,'#868b77',.04);Art.text(['las pequeñas revoluciones','cuidado: pincha','la última página'][page],666,695,19,'#929584',-.012);
  for(const s of stains){ctx.save();ctx.fillStyle=s.color;ctx.beginPath();ctx.ellipse(s.x,s.y,s.r*1.8,s.r,.6,0,TAU);ctx.fill();for(let i=0;i<7;i++){const a=i*2.4+s.seed;ctx.beginPath();ctx.arc(s.x+Math.cos(a)*s.r*2,s.y+Math.sin(a)*s.r*1.5,2+i%3,0,TAU);ctx.fill()}ctx.restore()}
  for(const s of spawns){ctx.save();ctx.globalAlpha=.4+Math.sin(clock*17)*.2;Art.ellipse(s.x,s.y,29+(1-s.t)*8,15,Art.red,1.8);Art.line([[s.x-8,s.y-8],[s.x+8,s.y+8]],Art.red,2);Art.line([[s.x+8,s.y-8],[s.x-8,s.y+8]],Art.red,2);Art.text('!',s.x,s.y-29,27,Art.red);ctx.restore()}
  for(const e of enemies)if(e.wind>0){ctx.save();ctx.globalAlpha=.2;const r=e.type==='boss'?72:31;Art.ellipse(e.x,e.y+15,r,r*.5,Art.red,3,Art.red);ctx.setLineDash([9,8]);Art.line([[e.x,e.y],[e.x+Math.cos(e.aim)*(e.type==='boss'?330:180),e.y+Math.sin(e.aim)*(e.type==='boss'?330:180)]],Art.red,6);ctx.restore()}
  for(const d of drops){ctx.save();ctx.globalAlpha=d.t<3?.5+Math.sin(clock*12)*.4:1;Art.text('♥',d.x,d.y+Math.sin(clock*5)*6,31,Art.red);ctx.restore()}
  for(const g of ghosts)Art.player(g.x,g.y,clock,{angle:g.a,alpha:g.t*1.3,dash:1});
  const actors=[...enemies.map(e=>({y:e.y,draw:()=>Art.enemy(e,clock)})),{y:player.y,draw:()=>Art.player(player.x,player.y,clock,{angle:player.angle,walk:player.walk,attack:player.attack/.19,dash:player.dash,alpha:player.invuln>0&&Math.floor(clock*15)%2?.45:1,hurt:player.invuln>.85})}];actors.sort((a,b)=>a.y-b.y);for(const a of actors)a.draw();
  for(const e of enemies)if(e.hp<e.maxHp&&e.type!=='boss'){ctx.fillStyle='#26394322';ctx.fillRect(e.x-18,e.y+37,36,3);ctx.fillStyle=Art.red;ctx.fillRect(e.x-18,e.y+37,36*e.hp/e.maxHp,3)}
  for(const s of shots){ctx.save();ctx.translate(s.x,s.y);ctx.rotate(s.angle);Art.line([[-13,0],[8,0]],Art.red,3);Art.line([[1,-5],[10,0],[1,5]],Art.red,2);ctx.restore()}
  for(const s of swings){ctx.save();const p=1-s.t/s.max;ctx.globalAlpha=(1-p)*.85;ctx.translate(s.x,s.y);if(s.special){ctx.rotate(p*5);for(let i=0;i<3;i++){ctx.strokeStyle=i%2?Art.blue:Art.ink;ctx.lineWidth=8-i*2;ctx.beginPath();ctx.ellipse(0,0,s.r*p+20,(s.r*p+20)*.8,i,0,5.7);ctx.stroke()}for(let i=0;i<12;i++)Art.star(Math.cos(i*TAU/12)*s.r*p,Math.sin(i*TAU/12)*s.r*p,12,Art.gold,i)}else{ctx.rotate(s.a);const a=-1.3+p*1.9;ctx.strokeStyle=s.heavy?Art.gold:Art.blue;ctx.lineWidth=s.heavy?15:9;ctx.beginPath();ctx.arc(0,0,s.r*.84,a,a+1.7);ctx.stroke();ctx.strokeStyle=Art.paper;ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,s.r*.87,a,a+1.7);ctx.stroke();}ctx.restore()}
  for(const p of particles){ctx.save();ctx.globalAlpha=clamp(p.t/p.max,0,1);ctx.fillStyle=p.color;ctx.beginPath();ctx.ellipse(p.x,p.y,p.r,p.r*.6,Math.atan2(p.vy,p.vx),0,TAU);ctx.fill();ctx.restore()}
  for(const t of texts){ctx.save();ctx.globalAlpha=Math.min(1,t.t*3);Art.text(t.text,t.x,t.y,t.size,t.color,-.08);ctx.restore()}
  if(bannerTime>0){ctx.save();ctx.globalAlpha=Math.min(1,bannerTime*2,(2.5-bannerTime)*3);ctx.fillStyle='#f4efd9db';ctx.fillRect(240,302,830,94);Art.text(banner,654,359,banner.length>22?43:55,Art.ink,-.025);Art.line([[403,376],[916,365]],Art.gold,5);ctx.restore()}
  if(turn>0&&!reduced){ctx.save();const p=turn/.85;ctx.fillStyle=Art.paper;ctx.shadowColor='#1c262d55';ctx.shadowBlur=25;ctx.beginPath();ctx.moveTo(1220-1150*p,46);ctx.lineTo(1220,46);ctx.lineTo(1220,735);ctx.lineTo(1220-900*p,735);ctx.closePath();ctx.fill();ctx.restore()}
  if(flash>0&&!reduced){ctx.fillStyle=player.invuln>.85?'#cf625b':'#f4efd9';ctx.globalAlpha=flash*1.2;ctx.fillRect(0,0,W,H);ctx.globalAlpha=1}ctx.restore();
}
function frame(now){const dt=Math.min(.033,(now-last)/1000||.016);last=now;if(freeze>0&&state==='play'){freeze-=dt;clock+=dt;shake=Math.max(0,shake-dt*20)}else update(dt);render();requestAnimationFrame(frame)}
$('start').onclick=beginIntro;$('skip').onclick=beginRun;$('sound').onclick=()=>{audioInit();muted=!muted;syncSound()};$('pause').onclick=pause;$('special').onclick=special;$('touch-special').onclick=()=>{audioInit();special()};$('touch-dash').onclick=()=>{audioInit();dash()};
$('help').onclick=()=>{setState('help');dialog('MANUAL DE SUPERVIVENCIA','No te dejes borrar.','WASD o flechas · moverte\nJ o mantener clic · combo de tres golpes\nEspacio o K · esquiva invulnerable\nE · garabato especial con la tinta al 100 %\nEsc o P · pausa\n\nEn móvil: joystick y botones en pantalla.\nLos avisos rojos anuncian ataques. Esquiva y contraataca.\nSupera tres páginas, elige mejoras y derrota a las tijeras.',null,'ENTENDIDO ↗',()=>{$('dialog').hidden=true;setState('menu');$('start').focus()})};
window.addEventListener('keydown',e=>{if(e.code==='Tab'&&!$('dialog').hidden){const list=[...$('dialog').querySelectorAll('button:not([hidden])')].filter(b=>!b.disabled);if(list.length){const i=list.indexOf(document.activeElement);if(e.shiftKey&&i<=0){list.at(-1).focus();e.preventDefault()}else if(!e.shiftKey&&i===list.length-1){list[0].focus();e.preventDefault()}}return}if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code)&&state==='play')e.preventDefault();if(e.repeat)return;if(e.code==='Escape'||e.code==='KeyP'){if(state==='help'){ $('dialog').hidden=true;setState('menu')}else pause();return}if(state!=='play')return;keys.add(e.code);if(e.code==='Space'||e.code==='KeyK')dash();if(e.code==='KeyE')special();if(e.code==='KeyJ')attack()});
window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{releaseControls();if(state==='play'||state==='intro')pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&(state==='play'||state==='intro'))pause()});
canvas.addEventListener('pointermove',e=>{if(e.pointerType==='touch')return;const r=canvas.getBoundingClientRect();pointer.x=(e.clientX-r.left)/r.width*W;pointer.y=(e.clientY-r.top)/r.height*H;pointer.used=true});canvas.addEventListener('pointerdown',e=>{if(e.button!==0||state!=='play'||e.pointerType==='touch')return;audioInit();pointer.down=true;canvas.setPointerCapture?.(e.pointerId);attack()});window.addEventListener('pointerup',()=>{pointer.down=false});canvas.addEventListener('pointercancel',()=>{pointer.down=false});canvas.addEventListener('contextmenu',e=>e.preventDefault());
let stickId=null,attackId=null;const stickEl=$('stick');function stickMove(e){if(e.pointerId!==stickId)return;const r=stickEl.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2,l=Math.hypot(x,y),k=Math.min(1,40/(l||1));stick.x=x*k/40;stick.y=y*k/40;stickEl.querySelector('i').style.transform=`translate(${x*k}px,${y*k}px)`;e.preventDefault()}
stickEl.addEventListener('pointerdown',e=>{stickId=e.pointerId;stickEl.setPointerCapture(e.pointerId);audioInit();stickMove(e)});stickEl.addEventListener('pointermove',stickMove);for(const type of ['pointerup','pointercancel','lostpointercapture'])stickEl.addEventListener(type,e=>{if(e.pointerId===stickId){stickId=null;stick.x=stick.y=0;stickEl.querySelector('i').style.transform=''}});
$('touch-attack').addEventListener('pointerdown',e=>{e.preventDefault();attackId=e.pointerId;touchAttack=true;e.currentTarget.setPointerCapture(e.pointerId);audioInit();attack()});for(const type of ['pointerup','pointercancel','lostpointercapture'])$('touch-attack').addEventListener(type,e=>{if(e.pointerId===attackId){touchAttack=false;attackId=null}});
// Optional browser-native tools use the same start flow as the visible controls.
if(document.modelContext?.registerTool){
 const lifecycle=new AbortController();
 const register=tool=>{try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}};
 const read=()=>({state,page:page+1,wave,score,health:player?.hp??null,ink:Math.floor(player?.ink||0)});
 register({name:'read_trazo_game',title:'Consultar TRAZO',description:'Read the current game state and score.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object.');return read()}});
 register({name:'start_trazo_game',title:'Abrir la libreta',description:'Start a new TRAZO game, including its opening scene. Available from the title or results screen.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object.');if(!['menu','dead','win'].includes(state))throw new Error('A game is already in progress.');beginIntro();return read()}});
 window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}
syncSound();requestAnimationFrame(frame);
})();
