const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {createCanvas,GlobalFonts}=require('@napi-rs/canvas');
const root=path.join(__dirname,'..');for(const [file,family] of [['caveat.ttf','Trazo'],['caveat-bold.ttf','Trazo'],['bangers.ttf','Bangers']])GlobalFonts.registerFromPath(path.join(root,'assets',file),family);
const context=vm.createContext({});vm.runInContext(fs.readFileSync(path.join(root,'art.js'),'utf8')+'\nglobalThis.Art=Art;',context);
const canvas=createCanvas(1280,800),ctx=canvas.getContext('2d'),A=context.Art;A.use(ctx);A.cover(0);
ctx.save();ctx.translate(178,209);ctx.rotate(-.035);ctx.textAlign='left';ctx.fillStyle=A.ink;ctx.font='bold 14px Arial';ctx.fillText('01   CUADERNO DE INCIDENTES',0,-24);ctx.font='207px Bangers';ctx.fillText('TRAZO',-4,145);ctx.fillStyle=A.red;ctx.fillText('!',426,148);ctx.strokeStyle=A.ink;ctx.lineWidth=1.5;ctx.strokeText('!',426,148);ctx.fillStyle=A.ink;ctx.font='35px Trazo';ctx.fillText('Un pequeño garabato.',0,206);ctx.font='bold 35px Trazo';ctx.fillText('Un problema muy grande.',0,243);A.rect(4,280,328,61,A.ink,A.ink,2);A.rect(0,274,328,61,A.red,A.ink,2);ctx.font='28px Bangers';ctx.fillStyle=A.paper;ctx.fillText('ABRIR LA LIBRETA',20,313);ctx.font='26px Arial';A.line([[284,315],[302,297]],A.paper,2);A.line([[286,297],[302,297],[302,313]],A.paper,2);ctx.font='21px Trazo';ctx.fillStyle=A.ink;ctx.fillText('por favor, no dibujar en los márgenes. ups.',0,376);ctx.restore();
ctx.save();ctx.translate(1060,150);ctx.rotate(.13);A.rect(-82,-36,163,75,A.paper,A.ink,2);A.text('UN JUEGO DE',0,-20,9,A.ink,0,'center','Arial');A.text('ASTRA',0,11,29,A.ink,0,'center','Bangers');A.star(-46,0,7,A.gold);A.text('100 % MALA CALIGRAFÍA',0,29,8,A.ink,0,'center','Arial');ctx.restore();
const small=createCanvas(640,400);small.getContext('2d').drawImage(canvas,0,0,640,400);fs.writeFileSync(path.join(root,'assets/cartridge.jpg'),small.toBuffer('image/jpeg',90));
console.log('Created updated TRAZO cartridge (640 × 400) from the original game renderer.');
